[package]
name = "steviegoodman/custodian"
description = "Simple Option and Result types."
version = "1.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"